Updated Xcode templates
- The installation paths are no longer hard coded; cmake now configures them so that Frameworks and libs can be installed somewhere else.
- No longer copy sndfile.framework but instead copy the new dependencies of the audio module.
- No longer copy .DS_Store to the install directory.

diff --git a/tools/xcode/templates/SFML/SFML App.xctemplate/TemplateInfo.plist.in b/tools/xcode/templates/SFML/SFML App.xctemplate/TemplateInfo.plist.in
--- a/tools/xcode/templates/SFML/SFML App.xctemplate/TemplateInfo.plist.in
+++ b/tools/xcode/templates/SFML/SFML App.xctemplate/TemplateInfo.plist.in
@@ -145,6 +145,12 @@ subject to the following restrictions:
                         <string># This shell script simply copies required sfml dylibs/frameworks into the application bundle frameworks folder.
 # If you're using static libraries (which is not recommended) you should remove this script from your project.
 
+# SETTINGS
+CMAKE_INSTALL_FRAMEWORK_PREFIX="@CMAKE_INSTALL_FRAMEWORK_PREFIX@"
+CMAKE_INSTALL_LIB_PREFIX="@CMAKE_INSTALL_PREFIX@/lib"
+SFML_MAJOR_VERSION=2
+FRAMEWORKS_FULL_PATH="$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/"
+
 # Are we building a project that uses framework or dylibs ?
 case "$SFML_BINARY_TYPE" in
     DYLIBS)
@@ -166,7 +172,7 @@ assert () # $1 is a boolean, $2...N is an error message
 {
     if [ $# -lt 2 ]
     then
-        error "Internal error in assert : not enough args"
+        error "Internal error in assert: not enough args"
     fi
 
     if [ $1 -ne 0 ]
@@ -192,40 +198,53 @@ copy () # $1 is a source, $2 is a destination
     assert $? "couldn't copy $1 to $2"
 }
 
+copy_framework() # $1 is the framework name (e.g. freetype)
+{
+    test $# -eq 1
+    assert $? "copy_framework() requires one parameter"
+    copy "$CMAKE_INSTALL_FRAMEWORK_PREFIX/$1.framework" "$FRAMEWORKS_FULL_PATH/$1.framework"
+}
+
+copy_lib() # $1 is the library name (e.g. sfml-graphics-d)
+{
+    test $# -eq 1
+    assert $? "copy_lib() requires one parameter"
+    lib="lib$1.$SFML_MAJOR_VERSION.dylib"
+    copy "$CMAKE_INSTALL_LIB_PREFIX/$lib" "$FRAMEWORKS_FULL_PATH/$lib"
+}
+
 require () # $1 is a SFML module like 'system' or 'audio'
 {
-    dest="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Frameworks"
-
     if [ -z "$1" ]
     then
         error "require() requires one parameter!"
     else
         # clean potentially old stuff
-        force_remove "$dest/libsfml-$1.2.dylib"
-        force_remove "$dest/libsfml-$1-d.2.dylib"
-        force_remove "$dest/sfml-$1.framework"
+        force_remove "$FRAMEWORKS_FULL_PATH/libsfml-$1.2.dylib"
+        force_remove "$FRAMEWORKS_FULL_PATH/libsfml-$1-d.2.dylib"
+        force_remove "$FRAMEWORKS_FULL_PATH/sfml-$1.framework"
 
         # copy SFML libraries
         if [ "$frameworks" = "true" ]
         then
-            copy "/Library/Frameworks/sfml-$1.framework" "$dest/sfml-$1.framework"
-        elif [ "$SFML_LINK_DYLIBS_SUFFIX" = "-d" ]
-        then
-            copy "/usr/local/lib/libsfml-$1-d.2.dylib" "$dest/libsfml-$1-d.2.dylib"
+            copy_framework "sfml-$1"
         else
-            copy "/usr/local/lib/libsfml-$1.2.dylib" "$dest/libsfml-$1.2.dylib"
+            copy_lib "sfml-$1$SFML_LINK_DYLIBS_SUFFIX"
         fi
 
         if [ "$1" = "audio" ]
         then
-            # copy sndfile framework too
-            copy "/Library/Frameworks/sndfile.framework" "$dest/sndfile.framework"
+            # copy "FLAC" "freetype" "ogg" "vorbis" "vorbisenc" "vorbisfile" frameworks too
+            for f in "FLAC" "freetype" "ogg" "vorbis" "vorbisenc" "vorbisfile"
+            do
+                copy_framework "$f"
+            done
         fi
 
         if [ "$1" = "graphics" ]
         then
             # copy freetype framework too
-            copy "/Library/Frameworks/freetype.framework" "$dest/freetype.framework"
+            copy_framework "freetype"
         fi
     fi
 }
